resource.AddFile("materials/Scavenger.png")
resource.AddFile("materials/Marathon.png")
resource.AddFile("materials/Lightweight.png")
resource.AddFile("materials/Recon.png")
resource.AddFile("materials/Hijacker.png")
resource.AddFile("materials/QuickFix.png")
resource.AddFile("materials/BonusArmor.png")
resource.AddFile("materials/Penetration.png")
resource.AddFile("materials/Juggernaut.png")
resource.AddFile("materials/SleightOfHand.png")
resource.AddFile("materials/BlindEye.png")

resource.AddFile("materials/Blast Shield.png")
resource.AddFile("materials/Mobility.png")
resource.AddFile("materials/Power.png")
resource.AddFile("materials/DangerClose.png")
resource.AddFile("materials/Engineer.png")
resource.AddFile("materials/Ninja.png")
resource.AddFile("materials/Assassin.png")
resource.AddFile("materials/Survivalist.png")

resource.AddFile("materials/Commando.png")
resource.AddFile("materials/DeadSilence.png")
resource.AddFile("materials/SitRep.png")
resource.AddFile("materials/Marksman.png")
resource.AddFile("materials/Stalker.png")
resource.AddFile("materials/Awareness.png")
resource.AddFile("materials/Martyrdom.png")
resource.AddFile("materials/TacticalMask.png")
resource.AddFile("materials/Scrambler.png")
resource.AddFile("materials/Executioner.png")

util.AddNetworkString("Tier1Perk")
util.AddNetworkString("Tier2Perk")
util.AddNetworkString("Tier3Perk")
util.AddNetworkString("PerkSpot")
util.AddNetworkString("HackerSpot")
util.AddNetworkString("PulsarSpot")
util.AddNetworkString("ResTimers")
util.AddNetworkString("TurretHacking")