hook.Add( "PopulateToolMenu", "MenuForSettings", function()
spawnmenu.AddToolMenuOption( "Options", "Player Perks", "PerksSettings", "Settings", "", "", function( panel )
	panel:ClearControls()

	panel:NumSlider("Armorer Mechanic", "CODPerksArmorerAltMechanic", 0, 2, 0)
	panel:Help("Change how the Armorer perk functions:\n 0 = Loot bodies for +5 armor. +25 max armor.\n 1 = Loot bodies for +5 armor. Spawn with 50 armor.\n 2 = +25 max armor. Spawn with 50 armor.")
	panel:NumSlider("Popup Icon X Pos", "CODPerksIconXPos", 0, 1, 2)
	panel:Help("Change the horizontal position of the Perk icon that pops up with Juggernaut/Blast Shield/Scavenger/Armorer. Default is 0.45")
	panel:NumSlider("Popup Icon Y Pos", "CODPerksIconYPos", 0, 1, 2)
	panel:Help("Change the vertical position of the Perk icon that pops up with Juggernaut/Blast Shield/Scavenger/Armorer. Default is 0.5")
	panel:NumSlider("Perk Icons X Pos", "CODPerksXPos", 0, 1, 2)
	panel:Help("Change the horizontal position of the perk icons. Default is 0.1")
	panel:NumSlider("Perk Icons Y Pos", "CODPerksYPos", 0, 1, 2)
	panel:Help("Change the vertical position of the perk icons. Default is 0.8")
	panel:CheckBox("Vertical/Horizontal Icons", "CODPerksVerticalHorizontal")
	panel:Help("Change the orientation of the perk icons. Off = Vertical, On = Horizontal")
	panel:CheckBox("Tier 1 Perk at top/bottom", "CODPerksTierPosition")
	panel:Help("Change the order in which perks are listed. Off = Tier 1 at top, On = Tier 3 at top")
	panel:NumSlider("Perk Icons Gap", "CODPerksGap", 0, 100, 0)
	panel:Help("Increase the gap between the perk icons. For use with bigger perk icons. Default is 0")
	panel:NumSlider("Perk Icons Size", "CODPerksIconSize", 0, 120, 0)
	panel:Help("Change the size of the perk icons. Default is 60")

	panel:NumSlider("T1 Perk X Pos", "CODPerksT1X", -100, 100, 2)
	panel:Help("Adjust the horizontal position of the T1 Perk (Blue)")
	panel:NumSlider("T1 Perk Y Pos", "CODPerksT1Y", -100, 100, 2)
	panel:Help("Adjust the vertical position of the T1 Perk (Blue)")
	panel:NumSlider("T2 Perk X Pos", "CODPerksT2X", -100, 100, 2)
	panel:Help("Adjust the horizontal position of the T2 Perk (Red)")
	panel:NumSlider("T2 Perk Y Pos", "CODPerksT2Y", -100, 100, 2)
	panel:Help("Adjust the vertical position of the T2 Perk (Red)")
	panel:NumSlider("T3 Perk X Pos", "CODPerksT3X", -100, 100, 2)
	panel:Help("Adjust the horizontal position of the T3 Perk (Yellow)")
	panel:NumSlider("T3 Perk Y Pos", "CODPerksT3Y", -100, 100, 2)
	panel:Help("Adjust the vertical position of the T3 Perk (Yellow)")
end)

spawnmenu.AddToolMenuOption( "Options", "Player Perks", "KeyBinds", "Key Bindings", "", "", function( panel )
	panel:ClearControls()
	panel:Help("Turret Hacking keybind")
	local binder = vgui.Create( "DBinder", frame )
	panel:AddItem(binder)
	function binder:OnChange( num )
		RunConsoleCommand("CODPerksInteract", input.GetKeyName(num))
	end
end)
end)