hook.Add( "PopulateToolMenu", "DivisionTalentsDefaults", function()
spawnmenu.AddToolMenuOption( "Options", "Player Perks", "DivDeft", "Division Defaults", "", "", function( panel )
	panel:ClearControls()

	local T1Choice = panel:ComboBox("Default Slot 1 Talent", "DivisionDefaultSlot1")
	T1Choice:SetSortItems(false)
	T1Choice:AddChoice("None")
	T1Choice:AddChoice("Adrenaline")
	T1Choice:AddChoice("Shock And Awe")
	T1Choice:AddChoice("Critical Save")
	T1Choice:AddChoice("Combat Medic")
	T1Choice:AddChoice("Battle Buddy")
	T1Choice:AddChoice("Wildfire")
	T1Choice:AddChoice("Demolition Expert")
	T1Choice:AddChoice("Fear Tactics")
	T1Choice:AddChoice("Chemical Spill")
	T1Choice:AddChoice("Evasive Action")
	T1Choice:AddChoice("Precision")
	T1Choice:AddChoice("Repo Reaper")
	T1Choice:AddChoice("On The Move")
	T1Choice:AddChoice("Chain Reaction")
	T1Choice:AddChoice("Stopping Power")
	T1Choice:AddChoice("One Is None")
	panel:Help("Default Slot 1 Talent to select on spawn")
	local T2Choice = panel:ComboBox("Default Slot 2 Talent", "DivisionDefaultSlot2")
	T2Choice:SetSortItems(false)
	T2Choice:AddChoice("None")
	T2Choice:AddChoice("Adrenaline")
	T2Choice:AddChoice("Shock And Awe")
	T2Choice:AddChoice("Critical Save")
	T2Choice:AddChoice("Combat Medic")
	T2Choice:AddChoice("Battle Buddy")
	T2Choice:AddChoice("Wildfire")
	T2Choice:AddChoice("Demolition Expert")
	T2Choice:AddChoice("Fear Tactics")
	T2Choice:AddChoice("Chemical Spill")
	T2Choice:AddChoice("Evasive Action")
	T2Choice:AddChoice("Precision")
	T2Choice:AddChoice("Repo Reaper")
	T2Choice:AddChoice("On The Move")
	T2Choice:AddChoice("Chain Reaction")
	T2Choice:AddChoice("Stopping Power")
	T2Choice:AddChoice("One Is None")
	panel:Help("Default Slot 2 Talent to select on spawn")
	local T3Choice = panel:ComboBox("Default Slot 3 Talent", "DivisionDefaultSlot3")
	T3Choice:SetSortItems(false)
	T3Choice:AddChoice("None")
	T3Choice:AddChoice("Adrenaline")
	T3Choice:AddChoice("Shock And Awe")
	T3Choice:AddChoice("Critical Save")
	T3Choice:AddChoice("Combat Medic")
	T3Choice:AddChoice("Battle Buddy")
	T3Choice:AddChoice("Wildfire")
	T3Choice:AddChoice("Demolition Expert")
	T3Choice:AddChoice("Fear Tactics")
	T3Choice:AddChoice("Chemical Spill")
	T3Choice:AddChoice("Evasive Action")
	T3Choice:AddChoice("Precision")
	T3Choice:AddChoice("Repo Reaper")
	T3Choice:AddChoice("On The Move")
	T3Choice:AddChoice("Chain Reaction")
	T3Choice:AddChoice("Stopping Power")
	T3Choice:AddChoice("One Is None")
	panel:Help("Default Slot 3 Talent to select on spawn")
	local T4Choice = panel:ComboBox("Default Slot 4 Talent", "DivisionDefaultSlot4")
	T4Choice:SetSortItems(false)
	T4Choice:AddChoice("None")
	T4Choice:AddChoice("Adrenaline")
	T4Choice:AddChoice("Shock And Awe")
	T4Choice:AddChoice("Critical Save")
	T4Choice:AddChoice("Combat Medic")
	T4Choice:AddChoice("Battle Buddy")
	T4Choice:AddChoice("Wildfire")
	T4Choice:AddChoice("Demolition Expert")
	T4Choice:AddChoice("Fear Tactics")
	T4Choice:AddChoice("Chemical Spill")
	T4Choice:AddChoice("Evasive Action")
	T4Choice:AddChoice("Precision")
	T4Choice:AddChoice("Repo Reaper")
	T4Choice:AddChoice("On The Move")
	T4Choice:AddChoice("Chain Reaction")
	T4Choice:AddChoice("Stopping Power")
	T4Choice:AddChoice("One Is None")
	panel:Help("Default Slot 4 Talent to select on spawn")

end)
end)