CreateConVar("DivisionDefaultSlot1", "None", 128, "Default Slot 1 talent to spawn with.")
CreateConVar("DivisionDefaultSlot2", "None", 128, "Default Slot 2 talent to spawn with.")
CreateConVar("DivisionDefaultSlot3", "None", 128, "Default Slot 3 talent to spawn with.")
CreateConVar("DivisionDefaultSlot4", "None", 128, "Default Slot 4 talent to spawn with.")

hook.Add("InitPostEntity", "DivisionTalentsFirstSpawn", function()

DefaultSlot1 = GetConVar("DivisionDefaultSlot1"):GetString()
DefaultSlot2 = GetConVar("DivisionDefaultSlot2"):GetString()
DefaultSlot3 = GetConVar("DivisionDefaultSlot3"):GetString()
DefaultSlot4 = GetConVar("DivisionDefaultSlot4"):GetString()

net.Start("NewTalent")
	net.WriteEntity(LocalPlayer())
	net.WriteString(DefaultSlot1)
net.SendToServer()
net.Start("NewTalent")
	net.WriteEntity(LocalPlayer())
	net.WriteString(DefaultSlot2)
net.SendToServer()
net.Start("NewTalent")
	net.WriteEntity(LocalPlayer())
	net.WriteString(DefaultSlot3)
net.SendToServer()
net.Start("NewTalent")
	net.WriteEntity(LocalPlayer())
	net.WriteString(DefaultSlot4)
net.SendToServer()

end)