hook.Add( "PopulateToolMenu", "PerkAColas", function()

	spawnmenu.AddToolMenuOption( "Options", "Player Perks", "PerkAColaMenu", "Perk-A-Colas", "", "", function( panel )
	panel:ClearControls()

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(15, 50)
PerkImage:SetSize(80,80)
PerkImage:SetImage("juggernog.png")
PerkImage:SetToolTip("Juggernog\n- Increases max health to 250.\n- Instantly heal for 150")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Juggernog")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(100, 50)
PerkImage:SetSize(80,80)
PerkImage:SetImage("doubletap.png")
PerkImage:SetToolTip("Double Tap\n- Deal double damage (ballistic weapons only.)\n- Increase weapon rate of fire by 20%")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Double Tap")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(185, 50)
PerkImage:SetSize(80,80)
PerkImage:SetImage("deadshotdaquiri.png")
PerkImage:SetToolTip("Deadshot Daquiri\n- Headshots deal double damage.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Deadshot Daquiri")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(15, 150)
PerkImage:SetSize(80,80)
PerkImage:SetImage("staminup.png")
PerkImage:SetToolTip("Stamin-Up\n- Move 7% faster\n- With suit Power: Double sprint power.\n- Without suit Power: Sprint 20% faster.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Stamin-Up")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(100, 150)
PerkImage:SetSize(80,80)
PerkImage:SetImage("phdflopper.png")
PerkImage:SetToolTip("PhD Flopper\n- Take no fall or explosion damage.\n- Falling from a height that would cause fall damage creates an explosion around you.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("PhD Flopper")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(185, 150)
PerkImage:SetSize(80,80)
PerkImage:SetImage("electriccherry.png")
PerkImage:SetToolTip("Electric Cherry\n- When reloading, enemies near you take a burst of shock damage.\n- Radius is based on ammo left in the magazine. Lower is better.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Electric Cherry")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(15, 250)
PerkImage:SetSize(80,80)
PerkImage:SetImage("vulureaid.png")
PerkImage:SetToolTip("Vulture Aid\n- Killed enemies drop ammo pickups that give ammo equivalent to 10% of your active weapons magazine size.\n- Weapons and ammo are highlighted through walls.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Vulture Aid")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(100, 250)
PerkImage:SetSize(80,80)
PerkImage:SetImage("deathperception.png")
PerkImage:SetToolTip("Death Perception\n- Enemies are highlighted by an orange aura.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Death Perception")
net.SendToServer()
end

local PerkImage = vgui.Create("DImageButton", panel)
PerkImage:SetPos(185, 250)
PerkImage:SetSize(80,80)
PerkImage:SetImage("elementalpop.png")
PerkImage:SetToolTip("Elemental Pop\n- Weapons have a 20% chance to also do elemental damage.\n- Includes fire, shock, acid (Brain Rot) and explosive\n- Fire ignites enemies, shock and explosive cause damage in a radius.\n- NPCs hit by Brain Rot are converted to your team for 10 seconds, after which they explode.")
PerkImage.DoClick = function()
net.Start("PerkACola")
net.WriteEntity(LocalPlayer())
net.WriteString("Elemental Pop")
net.SendToServer()
end

end)
end)