hook.Add( "PopulateToolMenu", "CodPerksDropMenuMain", function()
spawnmenu.AddToolMenuOption( "Options", "Player Perks", "CodPerksDropMenu", "CoD Perk Drops", "", "", function( panel )
	panel:ClearControls()

	panel:Help("Open Perk Drop Menu")
	local binder = vgui.Create( "DBinder", frame )
	panel:AddItem(binder)
	binder:SetValue(GetConVar("CODPerksDropPerk"):GetInt())
	function binder:OnChange( num )
		RunConsoleCommand("CODPerksDropPerk", num)
	end

	panel:ControlHelp("\nPlayer Perk Dropping settings:")
	panel:CheckBox("Drop perks on death", "CODPerksDropOnDeath")
	panel:Help("When enabled, players will drop all perks as pickups on death.")
	panel:CheckBox("Remove perks on death", "CODPerksRemoveOnDeath")
	panel:Help('If the "Drop perks on death" setting is enabled, dying will also remove all perks from the player.')
	panel:CheckBox("Auto-pickup perks", "CODPerksAutoPickup")
	panel:Help("When enabled, players will automatically pickup perks if they do not already have one in the same tier.")
	panel:NumSlider("Pickup Icon Distance", "CODPerksPickupIconDist", 0, 2056, 0)
	panel:Help("The distance at which the icon over perk pickups will be visible at.")

	panel:ControlHelp("\nNPC Perk Dropping settings:")
	panel:CheckBox("Hostile NPCs can drop perks", "CODPerksNPCDropPerks")
	panel:Help("Enable NPCs to drop perks when killed.")
	panel:CheckBox("Combine can drop perks", "CODPerksNPCDropPerksCombine")
	panel:Help("Allow Combine Soldiers and Metropolice to drop perks.")
	panel:CheckBox("Combine can drop perks", "CODPerksNPCDropPerksHunter")
	panel:Help("Allow Hunters to drop perks, with 10% extra drop chance.")
	panel:CheckBox("Zombies can drop perks", "CODPerksNPCDropPerksZombies")
	panel:Help("Allow Zombies and variants to drop perks. Chance is reduced by 5% (to a minimum of 1%), except for Poison Zombies.")
	panel:NumSlider("Perk Drop Chance", "CODPerksNPCDropPerksChance", 0, 100, 0)
	panel:Help("Percentage chance for an NPC to drop a perk. Stronger enemies have an additional 10% chance. Default is 7.")

	panel:ControlHelp("\nCrate Perk Dropping settings:")
	panel:CheckBox("Ammo Crates can drop perks", "CODPerksCrateDropPerks")
	panel:Help("When enabled, ammo crates can drop a random perk when broken.")
	panel:NumSlider("Perk Drop Chance", "CODPerksCrateDropPerksChance", 0, 100, 0)
	panel:Help("Percentage chance for an ammo crate to drop a perk. Default is 7.")

end)
end)